// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_01.Models;

#nullable disable

namespace Proyecto_01.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240202124323_seed-categorias")]
    partial class seedcategorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Proyecto_01.Models.Categoria", b =>
                {
                    b.Property<uint>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1u,
                            Nombre = "categoria1"
                        },
                        new
                        {
                            IdCategoria = 2u,
                            Nombre = "categoria2"
                        },
                        new
                        {
                            IdCategoria = 3u,
                            Nombre = "categoria3"
                        },
                        new
                        {
                            IdCategoria = 4u,
                            Nombre = "categoria4"
                        },
                        new
                        {
                            IdCategoria = 5u,
                            Nombre = "categoria5"
                        },
                        new
                        {
                            IdCategoria = 6u,
                            Nombre = "categoria6"
                        });
                });

            modelBuilder.Entity("Proyecto_01.Models.Producto", b =>
                {
                    b.Property<uint>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<uint>("IdCategoria")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyecto_01.Models.Producto", b =>
                {
                    b.HasOne("Proyecto_01.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto_01.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
